#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType gpuless

case "$WM_GPU" in
*CUDA*)
    (wmake $makeType cuda)
    ;;
esac


# ----------------------------------------------------------------- end-of-file
